### ISSUE TITLE
GeoNode front page styling stage I

### ISSUE THREAD

**Issue by deviirmr** [SeaBee-no/GeoNodeGeoViz#13]

**Comment by JamesSample** [comment]
@deviirmr I think the GeoNode styling looks nice! My only comment is that the "footer" (the part with all the partner logos) is so large that it takes up a lot of the screen when browsing maps. Is it possible to make the footer collapse-able? Or maybe make it smaller? If not, I suggest just removing it completely - we have nice branding on the main SeaBee website and I think the GeoNode site should focus on the data as much as possible.

**Comment by JamesSample** [comment]
Another minor addition that would be nice to include if possible: can we add **Date** to the list of options for filtering, please?

In the [GeoNode docs](https://docs.geonode.org/en/3.3.x/usage/data/finding_data.html) it looks as though date should be available as a filter option, but it's not currently exposed in our GeoNode. Hopefully this is easily configurable somewhere? Any ideas, @deviirmr? 

I think a common way of filtering for SeaBee users will be to filter by date and spatial extent, so if we can expose the "date" option too, that would be great.

**Comment by JamesSample** [comment]
Closing this, @deviirmr, as you've already resolved the footer issue. I'll create a new issue regarding the overall styling, as discussed earlier.
