### ISSUE TITLE
Drone mission overview map

### ISSUE THREAD

**Issue by JamesSample** [SeaBee-no/GeoNodeGeoViz#20]
The GeoNode page currently has tabs showing Data, Maps, GeoStories and Dashboards. 

It would be nice to have an additional link to an **overview map** showing all SeaBee missions on a single map, ideally with a sidebar listing the datasets, maps and GeoStories withgin the current extent. 

The map should start by showing the full extent of Norway and allow users to zoom in to easily see what datasets are available within their area of interest.

**Comment by deviirmr** [comment]
its done.
