### ISSUE TITLE
NodeODM job status page

### ISSUE THREAD

**Issue by deviirmr** [SeaBee-no/GeoNodeGeoViz#24]
In connection with the Seabee annual meeting in 2023 and the suggestion, it has been discussed to display the NodeODm job status at the GeoNode front-end side with a simple page,  This page will provide a list of the current NodeODM job statuses.

@JamesSample has already succeeded in retrieving the current job status within the [JupyterHub environment](https://github.com/SeaBee-no/seabeepy/blob/main/notebooks/check_processing_progress.ipynb). Moving forward, the plan is to explore how to integrate a portion of code into the Django environment and make it available through an API. The goal is to enable the GeoNode front-end to consume this API and display the up-to-date NodeODM job statuses, providing users with real-time information.
@knl88

**Comment by knl88** [comment]
Better fit for the https://github.com/SeaBee-no/GeoNodeGeoViz repo?

There will also be a subtask on the seabee-manifest repo on for allowing traffic to nodeodm.

**Comment by deviirmr** [comment]
What do you think? should we  implement this one in the current Seabee or seabee2.

**Comment by JamesSample** [comment]
Not a priority this year, at least. It's explicitly mentioned in the SeaBee2 proposal, so let's wait to see if we get funding for that first.

**Comment by deviirmr** [comment]
will follow in the seabee2
