### ISSUE TITLE
GeoNode email notification cobfigration

### ISSUE THREAD

**Issue by deviirmr** [SeaBee-no/GeoNodeGeoViz#25]
There is a need to enable GeoNode email notification. 
The notification with help GeoNode authenticate the first-time user registration in the portal and is also needed in case of change or forgetting the password.

In the initial test, we tried the following configuration at .env at the local development 
# EMAIL Notifications
```
EMAIL_ENABLE=True
DJANGO_EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
DJANGO_EMAIL_HOST=smtp.office365.com
DJANGO_EMAIL_PORT=587
DJANGO_EMAIL_HOST_USER=seabee.info@niva.no
DJANGO_EMAIL_HOST_PASSWORD=*******
DJANGO_EMAIL_USE_TLS=True
DJANGO_EMAIL_USE_SSL=False
DEFAULT_FROM_EMAIL='GeoNode <seabee.info@niva.no>'
```
# Users Registration
```
ACCOUNT_OPEN_SIGNUP=True
ACCOUNT_EMAIL_REQUIRED=True
ACCOUNT_APPROVAL_REQUIRED=False
ACCOUNT_CONFIRM_EMAIL_ON_GET=False
ACCOUNT_EMAIL_VERIFICATION=none
ACCOUNT_EMAIL_CONFIRMATION_EMAIL=False
ACCOUNT_EMAIL_CONFIRMATION_REQUIRED=False
ACCOUNT_AUTHENTICATION_METHOD=username_email
AUTO_ASSIGN_REGISTERED_MEMBERS_TO_REGISTERED_MEMBERS_GROUP_NAME=True
```

Notification seems working and it sends the notification, but instead of sending it to a new user for approval, it sends a notification back to the sender itself (seabee.info@niva.no). which is not the expected behaviour and needs to be further investigated. 
![image](https://github.com/SeaBee-no/GeoNodeGeoViz/assets/10088434/0baf12a7-a8d3-4a62-9555-34066f2cac00)
@JamesSample

**Comment by knl88** [comment]
Good notification seems to work, not sure I understand the screenshot, you as admin should get this notification shouldn't you?

Then I guess invites work also?

On a different note, perhaps you should add email confirmation and verification again?

**Comment by deviirmr** [comment]
Sorry, I mean user must receive a activation email in their inbox but instead sender is getting the activation email (screenshot ).
